patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-addr2line
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-ar
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-as
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-c++filt
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-cpp
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-dwp
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-elfedit
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-g++
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-gcc-13.3.1
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-gcc-ar
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-gcc-nm
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-gcc-ranlib
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-gcov
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-gcov-dump
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-gcov-tool
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-gdb
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-gdb-add-index
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-gdb-add-index-py
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-gdb-py
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-gfortran
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-gprof
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-ld
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-lto-dump
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-nm
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-objcopy
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-objdump
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-ranlib
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-readelf
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-size
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-strings
patchelf --set-interpreter ld-linux-x86-64.so.2 aarch64-none-linux-gnu-strip


